package main

// Generated by `harness workflows bootstrap --activate`. Enables the dynamic-
// workflows feature flag + declares each staged bundle as an active #Workflow,
// so `harness apply` compiles them to .claude/workflows/<name>.js (run as /<name>).
// Delete this file to deactivate (or set the flag off).

harness: {
	featureFlags: "standard_l4_dynamic_workflows": "on"
	workflowPolicy: enabled: true
	workflows: {
		"codebase-audit": {
			name:        "codebase-audit"
			owner:       "harness-bundled"
			description: "Fan-out correctness + security + performance sweep across the repo, adversarially verified."
			bodyRef:     "workflows/codebase-audit/codebase-audit.js"
			scope:       "project"
		}
		"deep-research": {
			name:        "deep-research"
			owner:       "harness-bundled"
			description: "Multi-source, cross-checked research on a question (args.question), synthesized with citations."
			bodyRef:     "workflows/deep-research/deep-research.js"
			scope:       "project"
		}
	}
}
