package schema

// 7-class provenance taxonomy per SPEC.md §4.4 (v1.0.8 alignment).
// Operator classifies inputs; the harness propagates the class through
// derived artifacts using the composition-via-untrusted rule.
#ProvenanceClass:
	"user-typed" |        // typed by a human at the prompt
	"workspace-internal" | // files committed to the workspace by humans
	"workspace-fetched" | // files brought in by the harness on operator instruction
	"network" |           // direct HTTP/S egress responses
	"mcp-internal" |      // MCP server vetted+self-hosted by the operator
	"mcp-external" |      // MCP server hosted by a third party
	"model-output"        // text generated by an LLM

// Trust levels per SPEC.md §4.4 — orthogonal to the class.
#TrustLevel: "trusted" | "mixed" | "untrusted" | "derived"

// Default trust mapping; operators may override per `#ProvenancePolicy.trustOverrides`.
#DefaultTrust: {
	"user-typed":         "trusted"
	"workspace-internal": "trusted"
	"workspace-fetched":  "mixed"
	"network":            "untrusted"
	"mcp-internal":       "mixed"
	"mcp-external":       "untrusted"
	"model-output":       "derived"
}

// Privacy-use tag (orthogonal to trust, per SPEC.md §4.4 v1.0.4 addition).
// Operators tag inputs that carry regulated data so DLP scanners (§8.2) can
// engage. Multiple tags allowed.
#ProvenanceUseTag:
	"pii" | "financial" | "health" | "secret" | "regulated-jurisdiction" | "confidential" | "public"

// #ProvenancePolicy — root type. Declares how the harness classifies and
// gates content by provenance.
#ProvenancePolicy: {
	// Required structural metadata; NEVER agentVisible.
	lifecycle:    "alpha" | "beta" | *"ga" | "deprecated"
	owner:        string
	agentVisible: false // structural per SPEC.md §4.1.2; compile-time deny

	// Per-class default trust override.
	trustOverrides?: [#ProvenanceClass]: #TrustLevel

	// Egress scanning toggles per SPEC.md §3.9.
	egressScan: {
		secretLeak:  *true | false
		piiDetect:   *true | false
		mcpIngress:  *false | true // v0.5.0 opt-in
	}

	// Quarantine policy for untrusted inputs.
	quarantineUntrusted: *true | false

	// Composition rule: any artifact deriving from at least one untrusted
	// input is itself untrusted. This is structural and not overridable.
	compositionRule: "any-untrusted-poisons-output"
}
