#!/bin/sh
# Generated by `harness hooks bootstrap`. ADVISORY hook — must exit 0 (never block).
# Review before relying on it; re-run bootstrap to regenerate.
# sources: https://code.claude.com/docs/en/hooks, https://github.com/anthropics/claude-code/blob/main/plugins/plugin-dev/skills/hook-development/SKILL.md, https://git-scm.com/docs/index-format, https://en.wikibooks.org/wiki/Git/Internal_structure, https://nesbitt.io/2026/01/17/lockfile-format-design-and-tradeoffs.html, https://arxiv.org/html/2505.04834v1
# guard-sensitive-edits (PreToolUse, advisory)
# Warns when an Edit/Write/MultiEdit targets a secret/key/credential store,
# SSH or cloud-config material, VCS internals (.git/), or a dependency lockfile.
# ADVISORY ONLY: prints to stderr and ALWAYS exits 0. Never blocks.

# --- Event guard: only act on PreToolUse -------------------------------------
case "${HARNESS_HOOK_EVENT:-PreToolUse}" in
  PreToolUse) ;;
  *) exit 0 ;;
esac

# --- Read the tool envelope (JSON) from STDIN --------------------------------
input=$(cat 2>/dev/null)

# --- Tool guard: only Edit / Write / MultiEdit ------------------------------
tool="${HARNESS_HOOK_TOOL:-}"
if [ -z "$tool" ] && command -v jq >/dev/null 2>&1; then
  tool=$(printf '%s' "$input" | jq -r '.tool_name // empty' 2>/dev/null)
fi
case "$tool" in
  Edit|Write|MultiEdit|"") ;;   # empty == undeterminable; fall through, no-op if no path
  *) exit 0 ;;
esac

# --- Extract the target file_path -------------------------------------------
fp=""
if command -v jq >/dev/null 2>&1; then
  fp=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
fi
if [ -z "$fp" ]; then
  # Dependency-light fallback: first "file_path":"..." in the envelope.
  fp=$(printf '%s' "$input" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)
fi

# Nothing to inspect -> silent no-op.
[ -n "$fp" ] || exit 0

# --- Normalize (treat \\ as a separator; derive basename; lowercase copies) --
path=$(printf '%s' "$fp" | tr '\\' '/')
base=${path##*/}
lpath=$(printf '%s' "$path" | tr '[:upper:]' '[:lower:]')
lbase=$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]')

reason=""

# 1) VCS internals -----------------------------------------------------------
case "$path" in
  .git|.git/*|*/.git|*/.git/*)
    reason="VCS internals (.git/) — Git manages this store; hand-editing objects/refs/index can corrupt the repository" ;;
esac
if [ -z "$reason" ]; then
  case "$path" in
    .svn|.svn/*|*/.svn/*|.hg|.hg/*|*/.hg/*)
      reason="VCS internals — editing version-control metadata can corrupt the repository" ;;
  esac
fi

# 2) SSH key / config store --------------------------------------------------
if [ -z "$reason" ]; then
  case "$lpath" in
    .ssh/*|*/.ssh/*) reason="SSH key/config store (.ssh/)" ;;
  esac
fi
if [ -z "$reason" ]; then
  case "$lbase" in
    id_rsa|id_dsa|id_ecdsa|id_ed25519|id_rsa.*|id_dsa.*|id_ecdsa.*|id_ed25519.*|known_hosts|authorized_keys)
      reason="SSH key material ($base)" ;;
  esac
fi

# 3) Cloud / tool credential stores ------------------------------------------
if [ -z "$reason" ]; then
  case "$lpath" in
    .aws/*|*/.aws/*)               reason="AWS credentials/config store (.aws/)" ;;
    .kube/*|*/.kube/*)             reason="Kubernetes credential store (.kube/)" ;;
    .gnupg/*|*/.gnupg/*)           reason="GnuPG keyring store (.gnupg/)" ;;
    .azure/*|*/.azure/*)           reason="Azure credential store (.azure/)" ;;
    .config/gcloud/*|*/.config/gcloud/*) reason="Google Cloud credential store (gcloud)" ;;
    .docker/config.json|*/.docker/config.json) reason="Docker registry credential store (.docker/config.json)" ;;
  esac
fi
if [ -z "$reason" ]; then
  case "$lbase" in
    kubeconfig) reason="Kubernetes credential file (kubeconfig)" ;;
  esac
fi

# 4) Secret / credential / key files (by name or extension) ------------------
if [ -z "$reason" ]; then
  case "$lbase" in
    .env|.env.*)
      case "$lbase" in
        .env.example|.env.sample|.env.template|.env.dist) ;;  # templates: skip
        *) reason="environment/secret file ($base)" ;;
      esac ;;
  esac
fi
if [ -z "$reason" ]; then
  case "$lbase" in
    .netrc|_netrc|.npmrc|.pypirc|.htpasswd|.dockercfg|credentials|credentials.*|secret|secrets|secrets.*|*.secret|*.secrets)
      reason="credential/secret file ($base)" ;;
  esac
fi
if [ -z "$reason" ]; then
  case "$lbase" in
    *.pem|*.key|*.pfx|*.p12|*.jks|*.keystore|*.kdbx|*.ppk|*.asc|*.gpg|*.pgp)
      reason="key/secret material ($base)" ;;
  esac
fi

# 5) Dependency lockfiles ----------------------------------------------------
if [ -z "$reason" ]; then
  case "$lbase" in
    package-lock.json|npm-shrinkwrap.json|yarn.lock|pnpm-lock.yaml|bun.lock|bun.lockb|deno.lock|\
    cargo.lock|poetry.lock|pipfile.lock|uv.lock|pdm.lock|\
    gemfile.lock|composer.lock|go.sum|gradle.lockfile|packages.lock.json|mix.lock|pubspec.lock|flake.lock)
      reason="dependency lockfile ($base) — regenerate via the package manager instead of hand-editing" ;;
  esac
fi

# --- Emit advisory guidance, then always succeed ----------------------------
if [ -n "$reason" ]; then
  printf '%s\n' "[guard-sensitive-edits] WARNING: $reason" >&2
  printf '  Target: %s\n' "$path" >&2
  printf '  Advisory only — the edit will proceed. Confirm this change is intentional and contains no leaked secrets.\n' >&2
fi

exit 0
