#!/bin/sh
# Generated by `harness hooks bootstrap`. ADVISORY hook — must exit 0 (never block).
# Review before relying on it; re-run bootstrap to regenerate.
# sources: https://docs.astral.sh/ruff/, https://docs.astral.sh/ruff/configuration/, https://docs.astral.sh/ruff/linter/, https://docs.astral.sh/ruff/installation/
# PostToolUse advisory hook: lint an edited Python file with ruff when the
# project actually configures ruff. ADVISORY ONLY — prints to stderr and
# always exits 0. Never blocks. No-op when the trigger condition is unmet.

# 1. React only to file-editing tools.
case "${HARNESS_HOOK_TOOL:-}" in
  Edit|Write|MultiEdit) ;;
  *) exit 0 ;;
esac

# 2. Read the tool envelope (JSON) from STDIN.
envelope=$(cat)

# 3. Extract the edited file path (first "file_path" in the JSON).
#    Dependency-light: grep + sed, no jq.
file=$(printf '%s' "$envelope" \
  | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' \
  | head -n 1 \
  | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')

# 4. Need a concrete, existing Python file (.py/.pyi) — else no-op.
[ -n "$file" ] || exit 0
case "$file" in
  *.py|*.pyi) ;;
  *) exit 0 ;;
esac
[ -f "$file" ] || exit 0

# 5. Walk up from the file's directory to find a ruff configuration, matching
#    ruff's own discovery: .ruff.toml, ruff.toml, or a pyproject.toml that
#    contains a [tool.ruff*] table (pyproject without [tool.ruff] is ignored).
dir=$(CDPATH= cd -- "$(dirname -- "$file")" 2>/dev/null && pwd) || exit 0
configured=0
d=$dir
while [ -n "$d" ]; do
  if [ -f "$d/.ruff.toml" ] || [ -f "$d/ruff.toml" ]; then
    configured=1; break
  fi
  if [ -f "$d/pyproject.toml" ] && grep -q '^[[:space:]]*\[tool\.ruff' "$d/pyproject.toml" 2>/dev/null; then
    configured=1; break
  fi
  parent=$(dirname -- "$d")
  [ "$parent" = "$d" ] && break   # reached filesystem root (POSIX / or Windows drive)
  d=$parent
done

# 6. No-op when ruff is not configured for this project.
[ "$configured" -eq 1 ] || exit 0

# 7. Need the ruff binary. If configured but absent, leave one helpful line.
if ! command -v ruff >/dev/null 2>&1; then
  printf '%s\n' "ruff (advisory): configured for this project but not found on PATH; skipping lint of $file" >&2
  exit 0
fi

# 8. Lint advisory. --force-exclude honors the project's exclude list even for
#    an explicit path; --quiet + --output-format concise keeps output compact.
out=$(ruff check --quiet --force-exclude --output-format concise -- "$file" 2>&1)
status=$?

# exit 0 = clean (or all auto-fixable and none reported); say nothing.
[ "$status" -eq 0 ] && exit 0

# Any other status (1 violations, 2 config/internal error): surface as advice.
if [ -n "$out" ]; then
  printf '%s\n' "ruff (advisory) flagged $file:" >&2
  printf '%s\n' "$out" >&2
  printf '%s\n' "To autofix where safe: ruff check --fix -- \"$file\"" >&2
fi

# ADVISORY: never block an edit.
exit 0
