#!/bin/sh
# Generated by `harness hooks bootstrap`. ADVISORY hook — must exit 0 (never block).
# Review before relying on it; re-run bootstrap to regenerate.
# Advisory PostToolUse formatter: run a detected formatter on the edited file
# IF the project configures it (or the formatter is a language default like
# gofmt). No-op and exit 0 otherwise — never blocks. file_path is extracted
# best-effort from the tool envelope on stdin.
envelope=$(cat)
path=$(printf '%s' "$envelope" \
  | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' \
  | head -n1 \
  | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"//; s/"$//')
[ -z "$path" ] && exit 0
root="${HARNESS_PROJECT_ROOT:-.}"
has() { [ -f "$root/$1" ]; }
case "$path" in
  *.go)
    command -v gofmt >/dev/null 2>&1 && gofmt -w "$path" 2>/dev/null \
      && echo "harness: gofmt $path" >&2
    ;;
  *.rs)
    { has rustfmt.toml || has .rustfmt.toml; } \
      && command -v rustfmt >/dev/null 2>&1 && rustfmt "$path" 2>/dev/null \
      && echo "harness: rustfmt $path" >&2
    ;;
  *.py)
    has pyproject.toml && command -v ruff >/dev/null 2>&1 \
      && ruff format "$path" >/dev/null 2>&1 && echo "harness: ruff format $path" >&2
    ;;
  *.js|*.jsx|*.ts|*.tsx|*.json|*.css|*.scss|*.md|*.html|*.yaml|*.yml)
    if has .prettierrc || has .prettierrc.json || has .prettierrc.js \
       || has prettier.config.js || has .prettierrc.yaml; then
      command -v prettier >/dev/null 2>&1 && prettier --write "$path" >/dev/null 2>&1 \
        && echo "harness: prettier $path" >&2
    fi
    ;;
esac
exit 0
