#!/bin/sh
# Generated by `harness hooks bootstrap`. ADVISORY hook — must exit 0 (never block).
# Review before relying on it; re-run bootstrap to regenerate.
# sources: https://vitest.dev/guide/cli, https://jestjs.io/docs/cli, https://playwright.dev/docs/test-cli, https://github.com/tarpas/pytest-testmon, https://docs.pytest.org/en/stable/how-to/usage.html
# PostToolUse / Test-on-change (ADVISORY).
# Suggests the fast, affected-tests command for the edited file's package.
# Never runs the full suite, never blocks: always prints to stderr and exits 0.

# React only to file-editing tools on PostToolUse. The harness already filters,
# but a stray invocation must be a silent no-op.
[ "${HARNESS_HOOK_EVENT:-PostToolUse}" = "PostToolUse" ] || exit 0
case "${HARNESS_HOOK_TOOL:-Edit}" in
  Edit|Write|MultiEdit) ;;
  *) exit 0 ;;
esac

# Read the tool envelope (JSON) from STDIN; pull out the edited path.
# No jq dependency: grab the first "file_path" string value, then unescape it.
input=$(cat 2>/dev/null) || exit 0
file=$(printf '%s' "$input" \
  | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
  | head -n 1)
[ -n "$file" ] || exit 0
# Unescape common JSON escapes in paths (Windows "\\", escaped "\/").
file=$(printf '%s' "$file" | sed -e 's/\\\\/\\/g' -e 's/\\\//\//g')

base=$(basename "$file")
srcdir=$(dirname "$file")

# Walk up from a start dir looking for any of the named files; print first hit.
# Iteration-capped so it terminates on relative, absolute, and Windows paths.
nearest() {
  _d=$1; shift; _i=0
  while [ "$_i" -lt 40 ]; do
    for _f in "$@"; do
      [ -f "$_d/$_f" ] && { printf '%s\n' "$_d/$_f"; return 0; }
    done
    _n=$(dirname "$_d")
    [ "$_n" = "$_d" ] && break
    _d=$_n; _i=$((_i + 1))
  done
  return 1
}

advise() {
  printf '[test-on-change] Edited %s\n' "$file" >&2
  printf '[test-on-change] Affected tests (advisory \u2014 not run automatically):\n' >&2
  printf '    %s\n' "$1" >&2
}

case "$base" in
  *.py)
    # Require some pytest config nearby, else stay silent.
    pyfile=$(nearest "$srcdir" pyproject.toml pytest.ini tox.ini setup.cfg) || exit 0
    pyroot=$(dirname "$pyfile")

    # If a testmon cache exists, that is the cheapest change-impacted selector.
    if nearest "$srcdir" .testmondata >/dev/null 2>&1; then
      advise "pytest --testmon   # change-impacted tests only (run from $pyroot)"
      exit 0
    fi

    is_test=0
    case "$base" in test_*.py|*_test.py|conftest.py) is_test=1 ;; esac
    case "$file" in */tests/*|*/test/*) is_test=1 ;; esac

    if [ "$is_test" = 1 ]; then
      advise "pytest \"$file\" -q"
      exit 0
    fi

    # Source file: map to a conventional test file, else scope to the nearest
    # tests dir, else the file's own package dir. Never the full suite.
    stem=${base%.py}
    for cand in \
      "$srcdir/test_$stem.py" "$srcdir/${stem}_test.py" \
      "$srcdir/tests/test_$stem.py" "$srcdir/../tests/test_$stem.py"; do
      if [ -f "$cand" ]; then
        advise "pytest \"$cand\" -q"
        exit 0
      fi
    done
    if [ -d "$pyroot/tests" ]; then
      advise "pytest \"$pyroot/tests\" -q   # no per-file test found; scoped to package tests"
    else
      advise "pytest \"$srcdir\" -q   # no per-file test found; scoped to package dir"
    fi
    exit 0
    ;;

  *.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs|*.mts|*.cts)
    # Require a package.json scope, else stay silent.
    pkg=$(nearest "$srcdir" package.json) || exit 0

    pwcfg=$(nearest "$srcdir" \
      playwright.config.ts playwright.config.js \
      playwright.config.mjs playwright.config.cjs playwright.config.mts || true)
    has_pw=0;   grep -q '"@playwright/test"' "$pkg" 2>/dev/null && has_pw=1
    has_vi=0;   grep -q '"vitest"'           "$pkg" 2>/dev/null && has_vi=1
    has_jest=0; grep -q '"jest"'             "$pkg" 2>/dev/null && has_jest=1

    is_spec=0;   case "$base" in *.spec.*|*.test.*) is_spec=1 ;; esac
    looks_e2e=0; case "$file" in *e2e*|*playwright*|*.e2e.*) looks_e2e=1 ;; esac

    if [ "$has_pw" = 1 ] && [ -n "$pwcfg" ] && [ "$is_spec" = 1 ] && [ "$looks_e2e" = 1 ]; then
      advise "npx playwright test \"$file\""
    elif [ "$has_vi" = 1 ]; then
      # vitest maps changed source files -> covering tests; --run avoids watch mode.
      advise "npx vitest related --run \"$file\""
    elif [ "$has_jest" = 1 ]; then
      advise "npx jest --findRelatedTests \"$file\""
    elif [ "$has_pw" = 1 ] && [ -n "$pwcfg" ] && [ "$is_spec" = 1 ]; then
      advise "npx playwright test \"$file\""
    else
      exit 0
    fi
    exit 0
    ;;

  *)
    exit 0
    ;;
esac
