#!/bin/sh
# Generated by `harness hooks bootstrap`. ADVISORY hook — must exit 0 (never block).
# Review before relying on it; re-run bootstrap to regenerate.
# sources: https://www.typescriptlang.org/docs/handbook/compiler-options.html, https://www.typescriptlang.org/tsconfig/#noEmit, https://www.typescriptlang.org/docs/handbook/project-references.html
# PostToolUse advisory hook: TypeScript typecheck-on-edit.
# Fires after Edit|Write|MultiEdit. When a .ts/.tsx file is edited, runs an
# advisory, emit-free type check: the project's own typecheck npm script if it
# declares one, otherwise `tsc --noEmit -p <nearest tsconfig>`.
# ALWAYS exits 0 and NEVER blocks (no exit 2). No-op when TypeScript is absent.

# --- Gate on event/tool (defensive; the harness already filters) -----------
[ "${HARNESS_HOOK_EVENT:-PostToolUse}" = "PostToolUse" ] || exit 0
case "${HARNESS_HOOK_TOOL:-Edit}" in
  Edit|Write|MultiEdit) ;;
  *) exit 0 ;;
esac

# --- Read the tool envelope (JSON) from STDIN ------------------------------
envelope=$(cat 2>/dev/null) || exit 0

# Extract the edited path from common envelope keys without a jq dependency.
extract() {
  printf '%s' "$envelope" | sed -n \
    "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" | head -n1
}
file=$(extract file_path)
[ -n "$file" ] || file=$(extract path)
[ -n "$file" ] || file=$(extract file)
[ -n "$file" ] || exit 0

# Unescape JSON-escaped slashes/backslashes so the path is usable.
file=$(printf '%s' "$file" | sed -e 's/\\\\/\\/g' -e 's/\\\//\//g')

# --- Trigger only for TypeScript source, never vendored code ---------------
case "$file" in *node_modules/*) exit 0 ;; esac
case "$file" in
  *.ts|*.tsx) ;;
  *) exit 0 ;;
esac

# --- Resolve the directory of the edited file ------------------------------
dir=$(dirname "$file" 2>/dev/null) || exit 0
[ -d "$dir" ] || dir=$(pwd)

# --- Walk up to locate the nearest marker file ----------------------------
find_up() { # $1=name $2=start-dir -> echoes containing dir, or nonzero
  d=$2
  while :; do
    [ -e "$d/$1" ] && { printf '%s' "$d"; return 0; }
    parent=$(dirname "$d")
    [ "$parent" = "$d" ] && return 1
    d=$parent
  done
}

# No tsconfig.json anywhere up the tree => project isn't TS-configured; no-op.
tsroot=$(find_up tsconfig.json "$dir") || exit 0
[ -n "$tsroot" ] || exit 0
pkgroot=$(find_up package.json "$dir") || pkgroot="$tsroot"

# --- Locate a LOCAL tsc; never trigger a network install (egress denied) ---
binroot=$(find_up node_modules "$dir") || binroot=""
tsc=""
[ -n "$binroot" ] && [ -x "$binroot/node_modules/.bin/tsc" ] && tsc="$binroot/node_modules/.bin/tsc"
[ -n "$tsc" ] || exit 0

# --- Optional run cap so the advisory check can't hang the agent -----------
runner=""
if command -v timeout >/dev/null 2>&1; then runner="timeout 120"
elif command -v gtimeout >/dev/null 2>&1; then runner="gtimeout 120"
fi

# --- Prefer the project's own typecheck script if declared -----------------
# (captures custom setups: tsc -b, project references, vue-tsc, etc.)
script=""
if [ -f "$pkgroot/package.json" ]; then
  for name in typecheck type-check tsc:check; do
    if grep -q "\"$name\"[[:space:]]*:" "$pkgroot/package.json"; then script=$name; break; fi
  done
fi

# Pick a package-manager runner for the script path, by lockfile.
pm=""
if [ -n "$script" ]; then
  if   [ -f "$pkgroot/pnpm-lock.yaml" ] && command -v pnpm >/dev/null 2>&1; then pm="pnpm"
  elif [ -f "$pkgroot/yarn.lock" ]     && command -v yarn >/dev/null 2>&1; then pm="yarn"
  elif command -v npm >/dev/null 2>&1; then pm="npm"
  fi
fi

# --- Run the advisory check ------------------------------------------------
if [ -n "$pm" ] && [ -n "$script" ]; then
  out=$(cd "$pkgroot" && $runner $pm run "$script" 2>&1); status=$?
  label="$pm run $script"
else
  # Emit-free, color-free, project-wide check (-p honors tsconfig settings;
  # passing a lone file would ignore tsconfig, so we check the project).
  out=$(cd "$tsroot" && $runner "$tsc" --noEmit --pretty false -p "$tsroot" 2>&1); status=$?
  label="tsc --noEmit -p $tsroot"
fi

# Timeout (124): advise, do not fail the agent.
if [ "$status" = "124" ]; then
  printf '%s\n' "[typecheck-on-edit] advisory typecheck timed out and was skipped (edited: $file)" >&2
  exit 0
fi

# --- Report (advisory only) ------------------------------------------------
if [ "$status" -ne 0 ]; then
  {
    printf '%s\n' "[typecheck-on-edit] advisory: TypeScript reported issues after editing $file"
    printf '%s\n' "  (ran: $label — non-blocking; review at your discretion)"
    printf '%s\n' "$out" | sed 's/^/  /' | head -n 50
  } >&2
fi

exit 0
