// POST /api/media/{mediaId}/publish/youtube — publish ONE finished demo video to YouTube.
// constitution §2: human-gated distribution (an operator button), NOT autopublish. P1: a thin
// Vercel route that validates, locates the S3 video, runs the two-phase idempotent dispatch, does
// one authenticated upload, and records the watch URL on the media asset. Secrets stay server-side.

import { NextResponse } from 'next/server';
import { z } from 'zod';
import { parseBody } from '@/app/lib/featureReview.ts';
import {
  getMediaForPublish,
  recordMediaPublication,
} from '@/app/lib/db/mediaAssets.ts';
import {
  beginApprovalDispatch,
  completeApprovalDispatch,
  deleteApproval,
} from '@/app/lib/db/approvals.ts';
import { getReleaseRun } from '@/app/lib/db/releaseRuns.ts';
import { fetchS3ObjectBytes } from '@/app/lib/s3Fetch.ts';
import { publishToYouTube, youtubeClientConfigured } from '@/app/lib/youtubePublish.ts';
import { YOUTUBE_DESCRIPTION_MAX, YOUTUBE_TITLE_MAX } from '@/app/lib/youtube.ts';
import { decideMediaPublish } from '@/app/lib/mediaPublishLogic.ts';
import { getDecryptedRefreshToken } from '@/app/lib/db/connections.ts';
import { GOOGLE_YOUTUBE_PROVIDER } from '@/app/lib/googleOAuth.ts';
import { optionalEnv } from '@/app/lib/env.ts';

// Aurora + S3 fetch + the authenticated YouTube upload require the Node.js runtime (not Edge).
export const runtime = 'nodejs';
// A multi-MB upload + OAuth exchange can take a while; raise the function ceiling past the default.
export const maxDuration = 300;

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const publishSchema = z
  .object({
    reviewer: z.string().trim().min(1).max(254),
    notes: z.string().trim().max(4000).optional(),
    title: z.string().trim().min(1).max(YOUTUBE_TITLE_MAX).optional(),
    description: z.string().trim().max(YOUTUBE_DESCRIPTION_MAX).optional(),
  })
  .strict();

interface RouteContext {
  readonly params: Promise<{ mediaId: string }>;
}

export async function POST(request: Request, context: RouteContext): Promise<NextResponse> {
  const { mediaId } = await context.params;
  if (!UUID_RE.test(mediaId)) {
    return NextResponse.json({ error: 'invalid media id' }, { status: 400 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'request body must be valid JSON' }, { status: 400 });
  }
  const parsed = parseBody(publishSchema, body);
  if (!parsed.ok) {
    return NextResponse.json(
      { error: 'invalid publish input', details: parsed.errors },
      { status: 400 },
    );
  }

  // A meaningful default title/description tied to the release (overridable in the body).
  const media = await getMediaForPublish(mediaId);
  const run = media === null ? null : await getReleaseRun(media.release_run_id);
  const dashboard = optionalEnv('DASHBOARD_BASE_URL', '');
  const defaultTitle =
    run === null ? 'ShipSignal demo video' : `${run.repo} ${run.head_ref} — demo`;
  const defaultDescription =
    `Demo video generated by ShipSignal for ${run === null ? 'a release' : `${run.repo} ${run.base_ref}…${run.head_ref}`}.` +
    (dashboard === '' ? '' : `\n\nReview: ${dashboard}/releases/${media?.release_run_id ?? ''}/media`);

  // Resolve the refresh token from the encrypted DB connection (Admin → Connections), falling back
  // to the env token. Dry-run when the client isn't configured, no token is connected, or the
  // PUBLISH_DRY_RUN override is set.
  const refreshToken =
    (await getDecryptedRefreshToken(GOOGLE_YOUTUBE_PROVIDER)) ??
    optionalEnv('YOUTUBE_REFRESH_TOKEN', '');
  const dryRun =
    !youtubeClientConfigured() || refreshToken === '' || optionalEnv('PUBLISH_DRY_RUN', '') !== '';

  const result = await decideMediaPublish(
    {
      mediaId,
      platform: 'youtube',
      reviewer: parsed.value.reviewer,
      title: parsed.value.title ?? defaultTitle,
      description: parsed.value.description ?? defaultDescription,
      // exactOptionalPropertyTypes: include notes only when present (never `notes: undefined`).
      ...(parsed.value.notes !== undefined ? { notes: parsed.value.notes } : {}),
    },
    {
      // `media` was already loaded for the title defaults; reuse it to avoid a second read.
      getMedia: async () => media,
      willDryRun: () => dryRun,
      beginDispatch: beginApprovalDispatch,
      completeDispatch: completeApprovalDispatch,
      deleteApproval,
      fetchVideoBytes: fetchS3ObjectBytes,
      publish: (input) => publishToYouTube(input, refreshToken),
      recordPublication: recordMediaPublication,
    },
  );
  return NextResponse.json(result.body, { status: result.status });
}
