"""T4 (spec 002) — runtime ``BoundaryReader`` + ``EvidenceSink`` over Aurora & S3.

P4 (Storage): redacted rows go to Aurora ``evidence_items``; the redacted full excerpt
goes to S3 referenced by key (never inlined). s3-rules: private bucket, TLS, keys are
sanitized (no traversal / untrusted bucket), server-side encryption on; the UI only
ever gets presigned URLs (generated by the Next.js layer, not here). aurora-rules: DSN
from env, TLS required, every statement parameterized.

Imported only by ``__main__`` at runtime (needs psycopg + boto3), so the unit gate
exercises the nodes against the in-memory fakes instead.
"""

from __future__ import annotations

import json
import re

import boto3
import psycopg

from release_worker.evidence_models import EvidenceRecord, ReleaseBoundary

# evidence_id / release_run_id are uuid4 hex or canonical UUIDs we mint — never
# attacker-controlled — but we still validate before composing an S3 key so a future
# caller can't smuggle a path-traversal segment (s3-rules: sanitize object keys).
_SAFE_KEY_SEGMENT = re.compile(r"\A[0-9a-fA-F-]{8,36}\Z")


def _safe_segment(value: str, label: str) -> str:
    if not _SAFE_KEY_SEGMENT.fullmatch(value):
        raise ValueError(f"unsafe {label} for S3 key")
    return value


class AuroraBoundaryReader:
    """Resolve a run's compare range from ``release_runs`` (PRD §5.2)."""

    def __init__(self, conn: psycopg.Connection) -> None:
        self._conn = conn

    def get_boundary(self, release_run_id: str) -> ReleaseBoundary:
        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT repo, base_ref, head_ref FROM release_runs WHERE id = %s",
                (release_run_id,),
            )
            row = cur.fetchone()
        if row is None:
            raise KeyError(release_run_id)
        return ReleaseBoundary(
            release_run_id=release_run_id,
            repo=row[0],
            base_ref=row[1],
            head_ref=row[2],
        )


class S3AuroraEvidenceSink:
    """Persist redacted evidence: blob → S3, row → Aurora.

    The bucket is private (Block Public Access enforced at the infra layer); objects
    are written with SSE and served to the UI only via short-expiry presigned URLs.
    """

    def __init__(self, conn: psycopg.Connection, s3_client: object, bucket: str) -> None:
        self._conn = conn
        self._s3 = s3_client
        self._bucket = bucket

    def store_blob(
        self, release_run_id: str, evidence_id: str, redacted_text: str
    ) -> str:
        run = _safe_segment(release_run_id, "release_run_id")
        ev = _safe_segment(evidence_id, "evidence_id")
        key = f"evidence/{run}/{ev}.txt"
        # mypy can't see boto3's dynamic client surface; call via the bound method.
        self._s3.put_object(  # type: ignore[attr-defined]
            Bucket=self._bucket,
            Key=key,
            Body=redacted_text.encode("utf-8"),
            ContentType="text/plain; charset=utf-8",
            ServerSideEncryption="AES256",
        )
        return f"s3://{self._bucket}/{key}"

    def record(self, item: EvidenceRecord) -> None:
        with self._conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO evidence_items (
                    id, release_run_id, evidence_type, source, source_url, repo,
                    file_path, symbol_name, raw_excerpt_s3_uri, redacted_excerpt,
                    risk_flags, metadata_json
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s::jsonb
                )
                """,
                (
                    item.evidence_id,
                    item.release_run_id,
                    item.evidence_type,
                    item.source,
                    item.source_url,
                    item.repo,
                    item.file_path,
                    item.symbol_name,
                    item.raw_excerpt_s3_uri,
                    item.redacted_excerpt,
                    json.dumps(list(item.risk_flags)),
                    json.dumps(item.metadata),
                ),
            )


def s3_client_from_env() -> object:
    """Build a boto3 S3 client from the ambient (role/OIDC) credentials.

    s3-rules: no static keys here — GitHub Actions assumes a role via OIDC and boto3
    picks the credentials up from the environment.
    """
    return boto3.client("s3")
