// Generated by `harness tools add`. A normal IR file — edit to tune.
package main

import schema "github.com/agent-harness/harness/schema"

harness: schema.#Harness & {
	tools: "fs-stage-artifact": schema.#Tool & {
		name:             "fs-stage-artifact"
		owner:            "me"
		description:      "Write a build artifact into the local staging dir."
		outputProvenance: "workspace-internal"
		writeClass:       true
		impl: {kind: "shell", bodyRef: "scripts/tools/fs-stage-artifact.sh"}
	}
}
