// Generated by `harness tools add`. A normal IR file — edit to tune.
package main

import schema "github.com/agent-harness/harness/schema"

harness: schema.#Harness & {
	tools: "run-test-suite": schema.#Tool & {
		name:             "run-test-suite"
		owner:            "me"
		description:      "Run the project's test command (long-running, may fail)."
		outputProvenance: "workspace-internal"
		circuitBreaker: {
			failureRateThreshold: 0.5
			rollingWindowSec:     60
			minimumRequests:      5
			halfOpenProbeCount:   2
			openDurationSec:      30
		}
		async:          true
		callbackEvents: ["tool.async.completed", "tool.async.failed"]
		concurrency: 1
		impl: {kind: "shell", bodyRef: "scripts/tools/run-test-suite.sh"}
	}
}
